apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-ui-ingress
  namespace: it-ui
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
    # appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard-sikshasathi-tech"
spec:
  rules:
    - host: ui.megcloud.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 80
