name: CI - PR Validation

on:
  pull_request:

  workflow_dispatch:

jobs:
  ci:
    uses: ITAssetManagementSystem/CommonWorkflows/.github/workflows/ci-aks.yml@main
    with:
      service_name: ui-service
      dockerfile_path: Dockerfile
      manifests_path: manifests
